### ISSUE TITLE
Info guide text

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/fit-count-app#111]
>  Portuguese version NERC-CEH/fit-count-app#8: string was appearing in English in the Portuguese version transifex string  #220 Jim: This is/was correct in transifex so appears to be an import error.

![image](https://user-images.githubusercontent.com/7383162/141316096-7fa9e1d1-1f2d-4916-aa22-edffa7f996e0.png)

@JimChiazzese1 It is unclear to me what this means. Is there a problem with the guide?

**Comment by JimChiazzese1** [comment]
The issue is on the information page - point 8 shows in English rather than Portuguese.


Identifique os visitantes florais em seus grupos mais amplos (abelhas, moscas, etc.) - qualquer um que você não reconheça deve ser contado como "outros insetos" ou "não sei".


![image](https://user-images.githubusercontent.com/84846811/141323845-3d0750db-92e8-4c98-8411-32ba477f1fe2.png)

**Comment by JimChiazzese1** [comment]
Still an issue with this in Portuguese

**Comment by JimChiazzese1** [comment]
[FitCount_Brazil_ImageCredits.docx](https://github.com/NERC-CEH/fit-count-app/files/7547553/FitCount_Brazil_ImageCredits.docx)

@kazlauskis

**Comment by kazlauskis** [comment]
Do you mean these two paragraphs being in English? This is because there is a missing translation for this in Portuguese.

<img width="450" alt="Screenshot 2021-11-17 at 09 05 38" src="https://user-images.githubusercontent.com/7383162/142150797-47b4de53-199e-40bc-b70e-15b029b08442.png">

**Comment by JimChiazzese1** [comment]
@kazlauskis Apologies Karolis, that's a little embarrassing, makes perfect sense. 
The Brazil team have completed the final translations, so should be able to reimport it all now
Jim

**Comment by kazlauskis** [comment]
No problem, this is done now.
