### ISSUE TITLE
Updates for Ireland beta

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#121]
- [x] Update credits

Jim: The photo credits are: Liam Lysaght, Colm Moriarty, John Walsh, Mary Douglas

- [x] On the Information circle page – is it possible to have our website link there? https://biodiversityireland.ie/surveys/fit-counts

Jim: Replace http://ukpoms.org.uk/fit-counts with the link above

- [x] Renaming of the three habitats

Jim: Waiting on response from Ireland 

- [x] Bumblebees screen two: can there be a number 1 pointing to the pollen ball

Jim: Imagine updated and uploaded

- [x] Solitary bees screen one: can you change it to 79 species (sorry! a new one just arrived – we haven’t publicised yet. That’s the last one we’ve been waiting on – Hairy-footed Flower Bee)

Jim: Master spreadsheet updated

- [x] Solitary bees screen three: It’s now only showing one photo. I had hoped to keep the 4 images, but to replace the UK number 3 with this photo. The text is updated correctly 

Jim: Images updated and uploaded

- [x] Hoverflies screen three: It’s now only showing one photo. I had hope to keep the 4 images, but to replace the UK number 1 with this photo. The text is updated correctly

Jim: images updated and uploaded

Updates to the Ireland demo. Just waiting to hear from Irealand about seriousness/requirement of having website and reports exactly matching app, which will tell us if we also need the new warehouseIDs for the three new habitats. 
Thanks
Jim

**Comment by kazlauskis** [comment]
Thanks, let me know when the warehouse IDs are finalised and we'll start the work on it.

**Comment by JimChiazzese1** [comment]
Ireland would like the habitats to appear differently in the reports to avoid confusion for users, so I will be requesting those from Martin as well, although would like to verify with Claire/David. My concern is that too many new targets and IDs jeopardises future cross country analysis.  Regarding the flowers, I think then, we only need to use the warehouse ID for red clover don't we?

**Comment by kazlauskis** [comment]
Yes, I think so. The species can be linked through synonyms. @DavidRoy

**Comment by DavidRoy** [comment]
For the different habitat names we could potentially use term-list synonymy?
@andrewvanbreda can you advise on options for this?

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy ,

As I am just jumping in here to this discussion,  I do not have a detailed understanding of the conversation.

If it is just reporting, synonyms could be used in the warehouse (although the report would need to understand which synonym to display if there is more than one non-preferred in same language).

If not just reporting, do the different habitat names need to appear differently on screen on a website?
If that is the case, is that an Irish specific website? or would these habitat names need to appear differently on the EU Spring site also?

Apologies for slightly vague reply

**Comment by JimChiazzese1** [comment]
The original request from Ireland was to change the name of some existing habitats so that they were more relevant/fit for purpose for Ireland:
Upland moorland to appear as Upland bog/heath
Lowland heath to appear as Lowland bog/heath
Waste ground or brownfield site to appear as Waste ground

Initially Ireland were fine to have just a wording change on the app with the count going into the existing categories (e.g. Upland bog/heath on the app recording as upland moorland on the warehouse).
However it's since apparent that changing on the app would not change reports and on the FITCount which could cause confusion to end users. Ireland do say though, that if it's not an easy fix it's something they could live with.

Ireland are keen to start promoting the use of the app as soon as possible, as survey season is getting underway, so I think whatever we do, either using synonyms or creating new target habitat IDs, would ideally happen quite quickly.

I can't comment on the Irish specific site or the EU Spring site, but happy to ask questions if someone can direct me on what's needed?
Given the time constraint, I wonder if it's quicker/easier to create new habitats and look to align later on?

Jim

**Comment by DavidRoy** [comment]
@JimChiazzese1 @andrewvanbreda.  Thanks for your inputs on this.  On balance, I think Jim is right about creating new habitat terms for this Ireland requirement.  The alternative of using synonym still leaves the problem of agreeing the preferred english version of the habitat names.  

@andrewvanbreda could we use the termlists_terms.meaning_id to link together the different names for the same habitat 'concept' in a similar way we do for taxa?

**Comment by andrewvanbreda** [comment]
Hi @JimChiazzese1 @DavidRoy @kazlauskis ,

OK I have had a think about this.

I suppose firstly to directly answer your question.
Setting the meaning_id would be equivalent to being a synonym.

I think one thing is clear.
The new entry must be linked to Ireland using the new country functionality, as we have done with other countries.

I think the actual question is whether the new entry in the Warehouse should be a synonym, or a new preferred term, or both.

The new code I have written for FIT Count/SPRING will then automatically show it when the user indicates they want Irish terms going into the data entry form.
The country code will also automatically appear on the sample and be used in edit mode to determine the correct terms to display.

I think the confusion is as follows:
As it has the same meaning as the original habitat term, it seems more natural to use a synonym.
But I am not sure if it is even possible to set a synonym to a different country to preferred.
Whether allowing that would be lovely and simple, or actually cause confusing chaos.

Could I get back to you later or tomorrow about this, as I have my head on other things at second, and hard to think about this.

One possible solution might be

- New preferred term linked to Ireland
- Use a synonym on the original habitat term AS WELL for reporting, reports can join because the synonym and preferred term have the same name.

It all depends on the result of an experiment to see if syonyms can have a country code of their own.

Please leave with me for the second.

Andy

**Comment by andrewvanbreda** [comment]
Hi @JimChiazzese1 @DavidRoy @kazlauskis,

I've had another think about this.

I think it would be a bad idea for me to sit here and suggest something really complex (that we then find has a problem down the line, and because of the complexity is really difficult to undo).

So I think it is best to start with something simple, we can then change that solution if needed because it is simple....or build on it.

If we start complicated it could be a mess to undo.

So in my opinion I would do this

- Add the Irish habitats as new preferred terms, linked to the Ireland county in the countries termlist as suggested.
This will ensure data entry forms show it correctly and the country is applied to the sample.

- If necessary, it can be added to the other non-iris habitat term as a synonym as well.
(if for instance we needed a report down the line where it was necessary to know they had the same meaning, the report could join on the term/synonym name).

- If that doesn't work, later down the line we can adjust the meaning_id on the preferred term instead.

As it is easy to add the synonym, I don't even think you need to do that right now.

If you add the preferred term, as long as the report takes a country parameter, it can show the right term.

Hope that helps. Feel free to adjust my suggestion as you want.

**Comment by DavidRoy** [comment]
Agreed.  Can you go ahead and setup the new terms for Ireland @andrewvanbreda

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy,
Apologies, as I jumped late  into this conversation can I just confirm the exact change you need (I think there is also another action we need, that we didn't mention before).
My understanding is as follows:

Termlist 667 (http://warehouse1.indicia.org.uk/index.php/termlist/edit/667?tab=terms) neeeds 3 new entries:
- Upland bog/heath
- Lowland bog/heath
- Waste ground

Those 3 entries to be linked to Ireland,

I believe we also need too carry out the following task:
- Link all the other terms to Ireland apart from the 3 habitats we won't be using for Ireland

If you can just confirm those actions, I can go ahead.

**Comment by DavidRoy** [comment]
@andrewvanbreda that is my understanding so please go ahead.
@kazlauskis @JimChiazzese1 to let us know if anything different is needed

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Done.
I forgot there would be entries for other countries, so I didn't add all the other terms to Ireland, only the ones which were already allocated to UK and the differences we mentioned.

The list attached to Ireland is therefore as follows:
Amenity grassland (usually mown short)
Churchyard
Farm crops or grassy pasture
Garden
Grassland with wild flowers (e.g. meadow)
Grassy verge or hedgerow edge
Lowland bog/heath
Parkland with trees
School grounds
Upland bog/heath
Waste ground
Woodland
Other - please describe below

The above list is alphabetical for clarity, but will use the same termlist sort order as UK on the actual system

**Comment by JimChiazzese1** [comment]
Many thanks for this Andrew - I assume there are new warehouse IDs for the new terms (Upland bog, Lowland bog, waste ground), can you share those please.
At this stage I don't have any access to warehouse end of things, which is perhaps something that will change as we progress, but for now, probably best I'm kept at a distance from that. 
Thanks Jim

**Comment by andrewvanbreda** [comment]
Hi @JimChiazzese1 

The termlist term IDs in the warehouse are:
Waste ground = 20079
Lowland bog/heath = 20080
Upland bog/heath = 20081

I assume these are the IDs you are after? (for example the old "Brownfield or other 'waste ground'" was 13567)

Hope that helps

**Comment by JimChiazzese1** [comment]
Many thanks Andrew - I believe that's exactly what's needed at this stage. Thanks Jim

**Comment by kazlauskis** [comment]
@JimChiazzese1 this is done now. The only one I wasn't sure is the `Bumblebees screen two: can there be a number 1 pointing to the pollen ball` task in the description, but if this is part of the images or the datasheet then this should be imported now too. Please close the ticket if all is done.

**Comment by JimChiazzese1** [comment]
Thanks Karolis. The bumblebee screen just involved an image edit, which I took care of and uploaded the replacement image, so that's now taken care of.
I'm afraid just one tiny change - the link on the information page is correct, but the URL text doesn't display only a hyperlink icon. Can we update that to also show the full URL hyperlinked to the location please.
Then we're done - I'll ask Ireland to verify and let you know we can push to Beta. Thanks Jim

![image](https://user-images.githubusercontent.com/84846811/161959768-0d3ee106-ede4-4637-8f67-76186916049f.png)
