### ISSUE TITLE
Automatically set/restrict language

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#145]
Germany and Chile have raised concerns about language settings. Should we have it set so that language is a two stage process. When selecting a country the language defaults to local language with the user having to go through region then language if they wish to change language. Should we also restrict it so that a count can only be done in the local language or the english related to that country?
I'm not really sure what happens if a user chooses a language from a country with a different set of target species, presumably the options will not be correct? 
@CCarvell

**Comment by CCarvell** [comment]
@JimChiazzese1 I am guessing the concerns are around your last point ie. a count being done in English but for the *wrong* country, in which case the options would not be correct as you suggest. Yes, selecting country first with a default to local language then proactively having to change language back to English would help this. @kazlauskis is this feasible in technical terms?
I can't remember if we imposed a country boundary on GPS locations to also restrict someone in Chile using the *UK* version.

**Comment by kazlauskis** [comment]
> I'm not really sure what happens if a user chooses a language from a country with a different set of target species, presumably the options will not be correct?

The options are tied to countries rather than languages. If a user selects Brazil, the options will be for Brazil but shown in the currently selected language. If that language doesn't have a translation, then it will default to English. Some countries will have multiple languages so we might want to keep this flexibility.

@JimChiazzese1 The app currently automates the language selection. At the point when the app is installed, it picks the language set from the device settings. So that if your primary device language is Spanish then it will use that by default and list the app countries' options in Spanish. Can you give me a scenario where this flow doesn't work?
