### ISSUE TITLE
Translations fix

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/fit-count-app#154]
The translation of text : “How about a rating on the Play Store then?” does not look the same in the demo app as in the transifex.  
The translation I wrote is “Hoćete li nas ocijeniti na Play Store?”, but in the demo application this text appears with capital letters starting each word “Hoćete Li Nas Ocijeniti Na Play Store?”

**Comment by JimChiazzese1** [comment]
Hi @kazlauskis I'm picking this up now that I'm working again. Does the above mean that this will be fixed when it's pushed to beta, rather than in the online demo? If so, then that's no problem. I'm talking to Ana currently and they're ready to go to beta.
Something you may be able to remind me of....once in Beta, do the submitted counts still get recorded and are accessible from the website. My understanding is that as long as the warehouse IDs have been updated then they will. Is that correct? (sorry for hijacking the fix!)
