### ISSUE TITLE
FITCount Portugal - Issues

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#171]
As per email. Please find attached issues reported by Portugal on initial review of Portugal FITCount app. 
Yellow appear to be issues related to app development/bugs, blue issues with content which have been updated.
Thanks
Jim

[Changes to current Beta version.docx](https://github.com/NERC-CEH/fit-count-app/files/11868305/Changes.to.current.Beta.version.docx)

**Comment by JimChiazzese1** [comment]
Thanks for all this Karolis. Seems I don't do this regularly enough to remember the issues from previous countrys! See comments inline below. 

> Hi @JimChiazzese1 , sorry, throwing the ball back to the Portuguese team/you 🙂
> 
> > Change the wasp drawing to the one sent before (i.e., the drawing below)
> 
> If you want a different illustration for an insect then you can do the same you've done for Brazil (e.g. `bumblebeesBr`) - you should first create a unique duplicate wasps entry in the datasheet, just for Portugal. In this case you can duplicate the `wasps` entry under a new ID like `waspsPT` in the `insects` sheet. This entry would then have the same warehouse ID and label etc, and would be assigned to Portugal only. The implication of this is that this id is linked to the `insect-guide-photos` sheet so like with the `bumblebeesBr` you have to duplicate the `wasps` photo annotations for the Portugal.

**Jim: Doh! I'd added the image but not added the new line to the spreadsheet, that's now done.**
> 
> > “Pollinator Groups / Grupos de Polinizadores” → Text in “Small insects (< 3 mm)” / “Insetos pequenos (< 3 mm)” is still in English, at least the first part
> 
> They haven't translated this one yet. Portugal's small insect texts start with "This category is for any insects under 3 mm long." and for other countries, it is "This category is for any insects under 3mm long." - note the extra space between the number and the millimetres type.

**Jim: Thanks. Now updated in Transifex, I didn't spot that gap in the 3 mm before so didn't see the empty translation**
> 
> > “Pollinator Groups / Grupos de Polinizadores” → In the first slide of “Big wildbees (bigger than honeybee) / Abelhas selvagens grandes (maiores que a abelha-do-mel)” - point no. 4 - the text is cut after opening the parenthesis
> 
> > “Pollinator Groups / Grupos de Polinizadores” → In the first slide of “Small wildbees (smaller than honeybee)” / ”Abelhas selvagens pequenas (mais pequenas que a abelha-do-mel)” - point no. 4 - the text is cut after opening the parenthesis
> 
> We don't allow chevron characters in the translations, these are reserved for text formatting (like < b > for bold, < i > italics, etc). One exception is the insect names which don't need any formatting. Maybe it's worth adding this to the datasheet guide?

**Jim:** That makes sense in theory, but bit confused as "Maior ou igual que a abelha-do-mel _(>= 10 mm)_" appears fine, but "(< 10mm)" as used in the small wildbees doesnt appear, so assume the = next to it makes a difference? That's just out of interest, portugal will need an alternative way to do it, so will give that some thought.
> 
> > In “Honeybees / Abelha-do-mel” - in slide 2, please remove 1 - “Eyes covered with hairs” / “Superfície dos olhos coberta de pelos” and the number 2 will be, now, the number 1.
> 
> This one is an annotation that should be removed from the datasheet, no?

**Jim: It's not i nthe spreadsheet, so think it's a bug of some sort - take a look at the attached video, certaintly something a little odd going on! On the first image in honeybee there was an error on teh spreadsheet where i'd duplicated the same caption twice. Portugal didn't notice that, i've not updated that in the spreadsheet, but could that duplication somehow cause the bug seen in that video**


https://github.com/NERC-CEH/fit-count-app/assets/84846811/2a59574d-4fe4-4497-950f-fd486c1c5863

**Comment by kazlauskis** [comment]
I love the video 👌🏻 The accumulation of the annotations happened because the app expected all the annotations to be unique. I have now fixed this issue. 

The < character typically starts a formatting block, and the < ends it, so the text cropping happens when the < is used. I would say that < or > shouldn't be used at all. The only exception is the species name, where we skip the formatting. Alternatively, I can easily disable the formatting options for the photo annotations, and we could use the < > then. What do you think?

**Comment by kazlauskis** [comment]
<img width="485" alt="Screenshot 2023-07-06 at 21 06 05" src="https://github.com/NERC-CEH/fit-count-app/assets/7383162/bb110161-47ed-49c0-a088-5cffc10bee2d">

These English source names below come from the datasheet, which we sync to Transifex. I have just pulled in the latest translations from Transifex, and these two appear to be translated OK.

Let's close this one, the demo app should be updated with the latest datasheet values and translations. Please reopen it if I missed something.

**Comment by JimChiazzese1** [comment]
Hi Karolis. Many thanks for this. All looking good. Just one issue I noticed. The image for Honeybees / Abelha-do-mel has not been updated. The original image was missing part of the image, but I edited and resupplied, but have just noticed the reason for it probably not showing. In the spreadsheet ID is 'honeybees' and Picture ID is PT1, but supplied image in 'honeybee_PT1' - assume best resolution is for me to rename the image file to 'honeybees_PT1'? Please confirm. Cheers Jim

**Comment by kazlauskis** [comment]
@JimChiazzese1 All these remaining issues come from the spreadsheet, onedrive or the Transifex. I've made these changes now, so apart from the missing translations, this is now done.

* There was a duplication of the Wasps in the Portuguese guide because we had to untag the old wasps entry from Portugal in the `insects` sheet.

![Screenshot 2023-07-13 at 11 03 26](https://github.com/NERC-CEH/fit-count-app/assets/7383162/88a6601c-2bd1-47d9-8e6d-c6f310e846b1)

* When an insect has a new ID in the `Insects` sheet, then all the photos referencing the old ID should be renamed to the new insect ID too. This also requires renaming the files in the OneDrive. Finally, although this step is optional since the new insect ID (i.e. `waspsPT`) is used only by Portugal it makes sense to use simpler photo IDs so I've also changed `PT1` into `1`,`PT2` into `2` etc.

Changes I've made inside `insect-guide-photos` spreadsheet:
![Screenshot 2023-07-13 at 11 14 39](https://github.com/NERC-CEH/fit-count-app/assets/7383162/7c401b0b-7b0f-458b-9d14-8c078bc5bb44)

* This still needs to be [translated in Transifex](https://app.transifex.com/ceh/fit-count-app/translate/#pt_PT/app/462027720?q=translated%3Ano):

![Screenshot 2023-07-13 at 11 16 00](https://github.com/NERC-CEH/fit-count-app/assets/7383162/615b23e7-5fc6-4d0b-be7f-e9ea002d2116)

* > The image for Honeybees / Abelha-do-mel has not been updated. The original image was missing part of the image, but I edited and resupplied, but have just noticed the reason for it probably not showing. In the spreadsheet ID is 'honeybees' and Picture ID is PT1, but supplied image in 'honeybee_PT1' - assume best resolution is for me to rename the image file to 'honeybees_PT1'? Please confirm. Cheers Jim

Yep, I've matched the file names now.

**Comment by JimChiazzese1** [comment]
Many thanks for making the changes and the explanations @kazlauskis - You would think by know I'd have mastered every aspect of the spreadsheet, but there's always something, so thanks for your patience! Just been into transifex and notice that the 'bigger than a honeybee' was translated 19hrs ago, so presumably Portugal just noticed that after raising the issue, so that should be the last change to be imported. It doesn't look like we're going to get anyone else joining the FITapp for the next few months at least. Sweden have nearly all their content, but have vanished and not responded to repeated emails, so we'll push them to next year. Thanks Jim

**Comment by kazlauskis** [comment]
No worries, I must also remind myself how this is set up. We update this complex spreadsheet infrequently, and it doesn't have any automatic validation or rules, so it's easy to miss inconsistencies. If we aren't planning to build a separate content management system for this yet, then improving the spreadsheet with Excel validations would be good so errors would be flagged earlier.

> Just been into transifex and notice that the 'bigger than a honeybee' was translated 19hrs ago, so presumably Portugal just noticed that after raising the issue, so that should be the last change to be imported.

Yes, it looks like this is done then. I am closing this ticket.
