### ISSUE TITLE
App screenshots for app stores and other marketing

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/fit-count-app#58]
Vilius and I have thought it would be nice to generate some pretty screenshots for the app stores and similar. Are you OK with these headlines over the screens?

![Simulator Screen Shot - iPhone 8 Plus - 2021-03-24 at 13 23 10_home_framed](https://user-images.githubusercontent.com/7383162/112672909-01025e80-8e5c-11eb-9882-9d85b45ff95d.png)
![Simulator Screen Shot - iPhone 8 Plus - 2021-03-24 at 14 43 01_location_framed](https://user-images.githubusercontent.com/7383162/112672899-fe076e00-8e5b-11eb-9127-ea1bb9eebf0c.png)
![Simulator Screen Shot - iPhone 8 Plus - 2021-03-24 at 14 45 12_flower_framed](https://user-images.githubusercontent.com/7383162/112672918-03fd4f00-8e5c-11eb-81fb-02fee0dca1da.png)
![Simulator Screen Shot - iPhone 8 Plus - 2021-03-24 at 13 25 42_count_framed](https://user-images.githubusercontent.com/7383162/112672916-0364b880-8e5c-11eb-97fa-5e2f3b88cdee.png)
![Simulator Screen Shot - iPhone 8 Plus - 2021-03-24 at 13 23 18_guide_framed](https://user-images.githubusercontent.com/7383162/112672913-02338b80-8e5c-11eb-9a16-6a3ca85fb0c5.png)

**Comment by kitenetter** [comment]
Thanks @kazlauskis they look good.

Three suggestions:
The map location looks a bit remote and potentially lacking flowers! Maybe use a suburban setting so there are gardens? I've used UKCEH Wallingford for a screenshot which arguably helps with the branding!:

![image](https://user-images.githubusercontent.com/16039111/112676430-53de1500-8e60-11eb-9587-21af9a2845ea.png)

For the flower photo, can you use this one, so that the uploaded photo is different to the one shown in the target list (which makes it look like there is some sor of automatic matching going on):

![Buddleia_CC](https://user-images.githubusercontent.com/16039111/112675698-6441c000-8e5f-11eb-99e2-1ba086daf802.JPG)

And for the insect guide, can you use the hoverfy page rather than the wasp page - hoverflies are the most frequent non-bee pollinators recorded:

![image](https://user-images.githubusercontent.com/16039111/112675894-a539d480-8e5f-11eb-8801-77faf78877e2.png)

**Comment by kazlauskis** [comment]
Excellent, thanks for the tips!
