### ISSUE TITLE
FIT Count website: Welsh pages for terms and privacy

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#60]
If you select Welch from the language dropdown, the home page and menu links are displayed in Welsh, but the links in the footer for the terms and privacy remain in English and take you to the English pages.

Can we set this os that choosing Welsh language also provides the correct links:
- Terms: https://fitcount.ceh.ac.uk/cy/telerau
- Privacy: https://fitcount.ceh.ac.uk/cy/hysbysiad-preifatrwydd

I'm not able to assign issues within this repository, but this one is for @BirenRathod please.

Could you also give me a role in this repository so that I can assign tasks etc.

**Comment by kazlauskis** [comment]
@kitenetter I have assigned you a different role in the repo so you should be able to manage the tickets yourself now.

It would be much better not to translate the actual URL links, just the page contents. We use the `/cy/` part to signify the selected language.

**Comment by kitenetter** [comment]
I'm not sure how the Welsh pages were originally set up. At the moment we have:
- https://fitcount.ceh.ac.uk/cy/hafan
- https://fitcount.ceh.ac.uk/cy/hysbysiad-preifatrwydd
- https://fitcount.ceh.ac.uk/cy/telerau

This seems to match the use of Welsh in the URLs on the PoMS website, e.g.:
- https://test-ceh-poms.pantheonsite.io/faqs
becomes:
- https://test-ceh-poms.pantheonsite.io/cy/cwestiynaucyffredin

So I'm not sure what needs to be done. I think it is preferable to use Welsh-language URLs when users select Welsh as their language.

**Comment by BirenRathod** [comment]
@kitenetter You can translate everything but not URL. so URL still be identify as /cy/privacy-notice. You can modify URL to English.

**Comment by BirenRathod** [comment]
@kitenetter Just in case if you can't find URL alias, I attached the screenshot which you can find in when you click "Edit" link of each page.
![image](https://user-images.githubusercontent.com/5941255/112971516-343c3a80-9147-11eb-8856-34305a33a404.png)

**Comment by kitenetter** [comment]
Okay. This is taking lots of time to sort out, so I want to be certain that I am understanding it correctly.

Are you saying that we should ALWAYS use English URLs, with the addition of "/cy", for ALL websites?

If so we also need to remove Welsh URLs from the PoMS website.

@DavidRoy @andrewvanbreda please can you confirm this is what you expect.

**Comment by BirenRathod** [comment]
@kitenetter I'm thinking about all pages but may be it is relevant to privacy &  terms pages, so @kazlauskis can able to link in the app. if I'm not wrong.

**Comment by kazlauskis** [comment]
We can go either way but I think these should be either `/cy/privacy-notice` and `/cy/terms` OR `/ysbysiad-preifatrwydd` and `/telerau`. Since the domain name is in English I would prefer to keep the URL paths in English too but use ISO language codes rather than translated paths. This way no translations would be needed and also avoiding potentially invalid characters in URLs. Having said this, it is more user friendly to translate the paths and also the domain name.

**Comment by andrewvanbreda** [comment]
I am easy with whatever you decide, but I think Karolis has a good point, if the domain name is in English only then it might be a bit odd to have Welsh page names mixed into he URL.

**Comment by kitenetter** [comment]
The Welsh versions of the Terms and Privacy notice are now fully updated.

Terms are at:
https://fitcount.ceh.ac.uk/cy/terms

Privacy:
https://fitcount.ceh.ac.uk/cy/privacy-notice

However, if I'm on the English Home page and I then choose Welsh, the wording and the links for the Terms and Privacy do not change. The only way to see the Welsh versions is to go to the English versions and then select Welsh again.

Can we set this so that choosing Welsh in one place enables Welsh versions in all other places?

**Comment by andrewvanbreda** [comment]
@kitenetter 
Hi Martin,
I have not used this site. Is this the "headless" site as it does not seem to allow me to register and therefore check it.
The problem is that the bottom area is the footer and held separately to the rest of the page.
So when switching to Welsh, the footer will remain in English until the footer has had its translation done.
You might be able to find how to Translate the footer looking up google about how to translate Drupal 8 footer.
I can't register on that site it seems, so I can't login to see.

**Comment by BirenRathod** [comment]
@kitenetter I amended the settings now , so footer now changes as per language selection.

**Comment by kitenetter** [comment]
The footer is still only being shown in English as far as I can see. However, no-one has asked us to change it as far as I'm aware, so I'm closing this for now.
