### ISSUE TITLE
Lots of blocked user accounts on the FIT Count website

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#74]
We have a lot of user accounts marked as "blocked" on the FIT Count website. Not sure why this is happening, and also whether I should edit them and unblock them (e.g. some are from PoMS partners who are presumably testing the app).

@kazlauskis not sure if this is an issue for you or for Biren, please assign accordingly.

**Comment by kazlauskis** [comment]
@kitenetter this means that people haven't yet verified their email addresses. We don't force verification and the user can still use the app, it is mandatory only when uploading the records. I think users are probably just exploring the app and since the app is still in the testing period there are few records being uploaded.

**Comment by kitenetter** [comment]
Okay, closing.
