### ISSUE TITLE
Cyprus Beta version final changes 28/07/21

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#96]
@kazlauskis 
1.	Will you take the revised English text from the Species-data.xls sheet? Some of Ioanna’s requests for changes are already showing in the English version of the “insect-guide-photos” sheet, but she has asked for slight changes to others. 
2.	Are you happy with the final list of habitat types for Cyprus? I hope this corresponds with what is listed as TRUE in the Species-data.xls sheet, as I have not edited this further.
3. I have changed the requested beetle photo in your Google drive but still need to edit one of the hoverfly photos once hearing back from Ioanna.

**Comment by kazlauskis** [comment]
@CCarvell 
1. Yes, I'll pull in any latest sheet changes to the app once you're done. 
2. Yes, there was an issue in the app which showed UK AND Cyprus habitats when Cyprus was selected. This was fixed now. Otherwise, the habitat types in the sheet is more for Ioanna to comment on.
3. Thanks, let me know when the photos are ready and I will add these in.

**Comment by CCarvell** [comment]
@kazlauskis 
1. I have made the requested changes to English text in the Species-data sheet. Relevant cells are coloured green to show where these edits occurred, more for my benefit to see that I have completed them all.
2.  Habitats seem sorted thanks
3.  New/ replacement photos for the insect guide are saved in your Google Drive:
hoverflies_4
beetles_3

Will you be able to send out a confirmation message and link once the Beta version is live?
many thanks
